### ISSUE TITLE
BSplayer: AttributeError. Exception info: "'NoneType' object has no attribute 'find'"

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1142]
In the log I have more than 10 pages with BSplayer errors.

Is it possible that you can do some magic in the code to solve this?

You can see the bazarr.log here at pastebin:

https://pastebin.com/nEBWFwGs

`07/10/2020 19:29:13|INFO    |root                            |Throttling bsplayer for 10 minutes, until 20/10/07 19:39, because of: AttributeError. Exception info: "'NoneType' object has no attribute 'find'"|`

**Comment by morpheus65535** [comment]
If you take a look at your debug.log file, you'll see that 99% of your issues are caused by ConnectTimeoutError exception. Your IP is probably blocked by them. And just to make sure to manage your expectations, BSplayer is probably the worst provider we have: it's unstable and they provide way less informations that we need to do a proper scoring. Don't expect anything good from that provider. That's a last resort provider.
