### ISSUE TITLE
Errors cause by some subtitle providers

### ISSUE THREAD

**Issue by Ivar418** [morpheus65535/bazarr#1426]
Ive recently added some providers, after doing this i was seeing a lot of errors about failed connections

For example:
Add (i believe) bsplayer as provider
Search for subtitles

**Expected behavior**
Should find subs without any errors in log

**Screenshots**
no ss but a log file:
https://ivarserver.ddns.net/nextcloud/s/dieQ7ALSEASG2gM

   Software
 - Bazarr: v 0.9.5
 - Radarr version v 3.2.0.5048
 - Sonarr version v 3.0.6.1196
 - OS: Debian 10

**Additional context**
the problem doesn't only occur with only 1 provide i believe. But i am not exactly sure wich ones.

So far ive seen in log:
Bsplayer
Podnapisi

I hope this is in your hands to fix

**Comment by morpheus65535** [comment]
Disable bsplayer, it's broken and I don't know how and when I'm gonna fix it.

It seems yifi is returning a 404 for a subtitles. If it occur again for multiple subtitles, open a specific issue for this provider.

I don't see any ther issue in your log. Seeing you're on Buster, you probably got an issue with Podnapisi because they use a week SSL protocol that is blocked in config of openssl on Buster.

**Comment by Ivar418** [comment]
Thank you for your reply.

Il use Yify as my only provider for a while so i can give u clean logs of it. Thank again.
