### ISSUE TITLE
Update Movie list from Radarr raised an exception

### ISSUE THREAD

**Issue by thisisbob3000** [morpheus65535/bazarr#1496]
I have been using bazarr for many months without issues. Sonarr works perfectly fine, but with radarr i get the following error when updating movie list: Job "Update Movie list from Radarr (trigger: interval[1:00:00], next run at: 2021-08-07 13:20:10 CEST)" raised an exception
Stack traceback: https://pastebin.com/wpZMSnuJ

I have no idea how to reproduce this as this just happend suddently without me doing any modifications. 

 - Bazarr: v0.9.62021-07-19Master
 - Radarr version 3.2.2.5080
 - Sonarr version 3.0.6.1265
 - OS: Linux

**Comment by morpheus65535** [comment]
I guess you restarted Radarr from scratch because from your log, I can see Radarr listing a movie with a radarrId already used. It's a primary key and is unique.

If it's not the case, Something want really wrong and you'll have to delete bazarr.db and let Bazarr reindex your stuff. You'll have to recreate and reassign languages profiles. Also, if you have some notification system you like to use, you'll have to reconfigure them.
