### ISSUE TITLE
Doesn't get list of movies from Radarr

### ISSUE THREAD

**Issue by dcplaya** [morpheus65535/bazarr#153]
**Describe the bug**
When I run a manual sync with Radarr, the following error happens in the log

```
26/09/2018 04:04:35|DEBUG|https://movies.TLDN.com:443 "GET /api/movie?apikey=**SECRET** HTTP/1.1" 200 None|
```

```
26/09/2018 04:04:37|ERROR|Job "Update movies list from Radarr (trigger: interval[0:05:00], next run at: 2018-09-26 04:09:33 PDT)" raised an exception|'Traceback (most recent call last):\n  File "/app/libs/apscheduler/executors/base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "/app/get_movies.py", line 100, in update_movies\n    added_result = c.executemany(\'\'\'INSERT INTO table_movies(title, path, tmdbId, languages, subtitles,`hearing_impaired`, radarrId, overview, poster, fanart, `audio_language`, sceneName, monitored) VALUES (?,?,?,(SELECT languages FROM table_movies WHERE tmdbId = ?), \'[]\',(SELECT `hearing_impaired` FROM table_movies WHERE tmdbId = ?), ?, ?, ?, ?, ?, ?, ?)\'\'\', movies_to_add)\nIntegrityError: UNIQUE constraint failed: table_movies.path'|
```

**To Reproduce**
Force a manual Radarr sync

**Expected behavior**
Should pull in a list of movies like it does for TV Shows

**Screenshots**
N/A

**Software (please complete the following information):**
 - Bazarr: 0.6.5 (Docker)
 - Radarr version  v 0.2.0.1198
 - Sonarr version v 2.0.0.5250
 - OS: Ubuntu

**Comment by morpheus65535** [comment]
Looks like you got two episode with the same path (occur with double episode). I've just reworked that part and I'll add a check to skip those one.

BTW, you're running developper branch? You can run in some issues like this one.

**Comment by dcplaya** [comment]
Yea its not big deal running dev. I can always change my docker to pull stable if I really want. But I would rather find bugs like this in dev and submit them to you before it gets pushed into stable!

**Comment by morpheus65535** [comment]
BTW you’re going to have to move to LSIO image. I eon’t be maintaining mine anymore.

**Comment by dcplaya** [comment]
I use the Suitarr docker and I believe that is still maintained.

**Comment by morpheus65535** [comment]
Yes, hotio maintain his own images.

**Comment by dcplaya** [comment]
> Looks like you got two episode with the same path (occur with double episode). I've just reworked that part and I'll add a check to skip those one.

Thats what you told me a few days ago and I checked my Radarr paths and I have a few movies that have the same path somehow. I was just waiting for you to add the check to skip those.

**Comment by morpheus65535** [comment]
You got multiple movie with the same path? How is this possible? How do you expect Bazarr to work on solid ground in that case?

**Comment by dcplaya** [comment]
Because it is completely possible for 2 movies of the same name to be released in the same year...

**Comment by morpheus65535** [comment]
I've added an ignore clause to skip those that don't respect constraint but you'll only get the first one with a path. It would require to remove the constraint for a seriously rare edge case.

**Comment by dcplaya** [comment]
For me that is perfectly fine. Maybe also throw a warning in the log and show which entries are duplicated.  I am editing my Radarr database now so it doesn't have the same path. It was only 1 movie.

![image](https://user-images.githubusercontent.com/1105320/46265576-9b2bfa80-c4dc-11e8-9426-8d20f3bd2eab.png)

**Comment by 4C3T** [comment]
Hi guys... Sorry to bump the thread, but I found this on google, on two separate searches.
Got the same error, and I can't quite find what's causing this.

I see dcplaya above here posted some fancy image with the text of something he edited...
Ehhh... Where and using what?
Guess that's a Linux version. I've got the Windows version v0.7.5.1 of Bazarr and 0.2.0.1358 of Radarr

I've got like some 3k5 movies, so it's very difficult to find duplicates. I do have several movies with the same names, but some are remakes. I do try to use default naming schemes like "Title (year).
Some, very few movies deviates from this though, but I'm working of fixing that a little at a time.
It's quite cumbersome to rename hundreds of movies (Note; Most do have "Title (year)", but many have dots and other crap in their folder names), so a little at a time.

I relatively recently installed Sonarr/Radarr/Bazarr on another computer and rebuilt everything. Bazarr I actually installed a couple of days ago. The previous install ran without a hitch until my server's one partition on the SSD had a nervous breakdown due to power outage (Lightning strike in a power station), so I had to reinstall everything, and Bazarr was shelved at that time.

Anywhoo, this time around I didn't add any directories in the config pages, and I honestly cannot remember doing that the last time, so I just left those blank, and it seemed to work anyways.
It downloaded about 700-ish subs.

Then (!!!), I noticed this yesterday after going through some of my missing movie files (Radarr), I noticed that some of the pathways for about a 100 movies had been altered for some FUBAR reason, so I changed the root paths for them.

As for some of the movies, I notice that I was missing subs, and had to reacquired these, and I turned to  Bazarr to get these.
This is when I noticed it refused to update the db.
I haven't tried to reinstall Bazarr, as I fear it'll be the same outcome.

So, any insights would be nice... Thank you

**Comment by morpheus65535** [comment]
@4C3T Please come to Discord support channel and provide a debug log so the support team is able to find the issue.

**Comment by 4C3T** [comment]
Ok. I'll do that a bit later. Gotta get some Zs right now

**Comment by 4C3T** [comment]
Sorry, forgot to get back on this one. Been quite busy past few days.

I don't seem to have a problem anymore as I did an overhaul of the entire db in Radarr by renaming all my movies (files and folders) that weren't using Name (year) format, then re-import everyone, and it seem like it's working, or, at least for now, so I look at this as solved.

**Comment by morpheus65535** [comment]
Ok keep me posted if you still have this issue.
