### ISSUE TITLE
[BUG] dexter new blood, legendas.tv

### ISSUE THREAD

**Issue by rigas40** [morpheus65535/bazarr#1627]
ther is a bug with
provider legendas.tv  search exact dexter new blood
and not Old seasons from other dexter

when try search some episode new tvshow dexter new blood, from season 1, get results from Old seasons serie dexter

seems there is not correct parse of name tvshow

**Comment by morpheus65535** [comment]
It's working as expected. You get "Dexter" subtitles here because Sonarr provide it as an alternate title to "Dexter: New Blood':
![image](https://user-images.githubusercontent.com/5130500/144310850-874701f9-be82-4755-85fb-a9a9fc331595.png)
There's not much we can do about it. Sonarr shouldn't do this.

**Comment by jimger** [comment]
That's the same also for greek providers

**Comment by morpheus65535** [comment]
@jimger the issue is with Sonarr, not with providers.

**Comment by morpheus65535** [comment]
Nothing more to do here.
