### ISSUE TITLE
I Can't find Anime subtitle in subscene ( Arabic Subtitle )

### ISSUE THREAD

**Issue by xVoldx** [morpheus65535/bazarr#1749]
**Describe the bug**
It seem bazarr can't find any arabic subtitle for anime in subscene.
Here is the log https://gist.githubusercontent.com/xVoldx/a46c8a21211763b424ba8e90970c39a2/raw/e79b95c0ec257614061fe01109e1c425e7a52e12/bazarr.log

**To Reproduce**
1. Using manual or automatic subtitle search.

**Expected behavior**
Using manual or automatic subtitle search still can't find any subtitle. As you can see in the screenshot, the subtitle is available.

**Screenshots**

![image](https://user-images.githubusercontent.com/62064902/156431980-6d7695a8-2a4a-429c-8913-b8da408808c4.png)

**Software :**
 - Bazarr: v1.0.3
 - Radarr Version: 4.0.4.5922
 - Sonarr Version: 3.0.6.1342
 - OS: Linux-5.11.0-1023-oracle-aarch64-with-glibc2.29
 - Python Version 3.8.10

**Comment by morpheus65535** [comment]
Anime is unsupported and may or may not work because of episode numbering. 

In this specific case, Subscene doesn't return a season number and series name doesn't match (different language).

**Comment by 5cat** [comment]
Hey @morpheus65535 , may I ask if you know a provider that does have the metadata for bazarr to parse episodes for anime or tv related content?

**Comment by morpheus65535** [comment]
> Hey @morpheus65535 , may I ask if you know a provider that does have the metadata for bazarr to parse episodes for anime or tv related content?

Bazarr is really bad with anime. Episodes numbering is really causing trouble with providers.

**Comment by Mi3liX9** [comment]
Have you got any solution?

**Comment by Eisa01** [comment]
@morpheus65535
Some suggestions I am considering, since this issue is basically affecting the anime category as a whole.

I am guessing there are two main concerns towards finding anime subtitles.
1 - Multiple title names
2 - Multiple episode numbering options. Seasonal / Absolute Numbering. (Also, pair that with some websites not even having proper API to find match based on id "looking at Subscene")

**For multiple title names:**
What is the feasibility of falling back to multiple titles to grab possible show names.
"Stops when title matches (priority from top-down)"
1. Title
2. Folder-name
3. Perhaps utilize [guessit](https://github.com/guessit-io/guessit) or similar / already available parsers to fetch additional titles?

**For episodes that are not finding a proper match, fallback using regex:**
1. Regex will get title of show, and episode number.
2. Episode number will start as seasonal and fallback to absolute.
3. Title could be fetched also from the file name, if a match is not available from the above.
4. The same regex will apply to look for content in websites that do not have proper API.

Apologies if the ideas are not even considerable since I did not review the code, and thanks for Bazarr. I am a fan =)

**Comment by morpheus65535** [comment]
@Eisa01 thanks for your suggestions. We already use guessit under the hood, the issue is simply that we don't use absolute numbering during search so subtitles that could be a match are just excluded because episode number (and season of course) doesn't match. We already have something in mind regarding this, there's just no ETA.
