### ISSUE TITLE
Increase embeddedsubtitles time out

### ISSUE THREAD

**Issue by nitschis** [morpheus65535/bazarr#1797]
How can we change the time for embeddedsubtitles provider? It is set to 10 minutes, which is not enough when extracting some files on cloud drives. 

Unrelated, but out of interest, I would like to know why the whole file has to be read to extract subtitles?

Thank you.

**Comment by morpheus65535** [comment]
@vitiko98 could probably answer those questions.

**Comment by vitiko98** [comment]
We could add a timeout option. Keep in mind, though, that more than ten minutes per subtitle is sub-optimal; I would not recommend extracting subtitles from cloud files that big. As a partial solution, you could try tools like [mergerfs](https://github.com/trapexit/mergerfs) alongside `embeddedsubtitles`' mergerfs mode.

> Unrelated, but out of interest, I would like to know why the whole file has to be read to extract subtitles?

Due to the [nature of some video containers](https://www.matroska.org/technical/diagram.html), you can't just pick decoded streams separately.

**Comment by vitiko98** [comment]
> Could you direct me to the file where the timeout is defined? At least I could change it manually for now.

Change 

https://github.com/morpheus65535/bazarr/blob/1a45fa67bc58c06e76c4d8f6af8831affacb0989/libs/subliminal_patch/providers/embeddedsubtitles.py#L188

to

`extracted = container.extract_subtitles(list(streams), self._cache_dir, timeout=SECONDS_INTEGER) 
`

**Comment by vitiko98** [comment]
I'm gonna implement the timeout option in the next hours. It'll be available in the next beta.

**Comment by nitschis** [comment]
Awesome. Thank you very much.

**Comment by vitiko98** [comment]
Done

**Comment by nitschis** [comment]
Thank you very much!

It might be a good idea to add an info box “extraction timeout” or something similar. As a user, unknown of this post would have no idea what the setting is for.

**Comment by vitiko98** [comment]
> Thank you very much!
> 
> It might be a good idea to add an info box “extraction timeout” or something similar. As a user, unknown of this post would have no idea what the setting is for.

This will be fixed in the future with the UI rework of @LASER-Yi
