### ISSUE TITLE
Bazarr constantly syncing episodes

### ISSUE THREAD

**Issue by Meyu-Sys** [morpheus65535/bazarr#1969]
**Describe the bug**
Bazarr is constantly trying to sync episodes 
in tasks refresh button is constantly blinking

**To Reproduce**
seems to happen on every startup

**Expected behavior**
Tasks should not be refreshing constantly

**Screenshots**
![image](https://user-images.githubusercontent.com/86107480/195344471-3c1002d0-b0b5-40fc-8705-d73e462c0e01.png)

**Software (please complete the following information):**
 - Bazarr: version 1.1.1 
 - OS: Docker Hotio latest/stable image

**Comment by Meyu-Sys** [comment]
I am sorry, i forgot. I will put it up late

**Comment by Meyu-Sys** [comment]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/9788311/bazarr.log)
here you go sorry for not attaching it earlier

**Comment by halali** [comment]
Did you try at least read some lines from log?

Is full of this error msg.

BAZARR cannot parse JSON returned by SignalR feed. This is caused by a permissions issue when Sonarr try to access its /config/.config directory.Typically permissions are too permissive - only the user and group Sonarr runs as should have Read/Write permissions (e.g. files 664 / folders 775). You should fix permissions on that directory and restart Sonarr. Also, if you're a Docker image user, you should make sure you properly defined PUID/PGID environment variables. Otherwise, please contact Sonarr support.|
