### ISSUE TITLE
How to install MediaInfo? (Windows)

### ISSUE THREAD

**Issue by StarSmasher44** [morpheus65535/bazarr#2035]
Sorry for issuing this as a bug report firstly, I tried the discord... Link is dead. Wiki... Link is dead. I searched the web and I searched the github, as well as bazaar itself.. But found nothing.

I have Bazarr running on Windows (Server), I figured installing MediaInfo was as simple as downloading the GUI version and calling it a day, but Bazarr doesn't seem to just take it. Missing binaries error.

How does one install MediaInfo for bazarr?

EDIT:
The error I get is this:

Traceback (most recent call last):
  File "c:\\bazarr\\bazarr\\subtitles\\utils.py", line 47, in get_video
    refiner(original_path, video)
  File "c:\\bazarr\\bazarr\\subtitles\\refiners\\ffprobe.py", line 32, in refine_from_ffprobe
    data = parse_video_metadata(file=path, file_size=file_id[\'file_size\'],
  File "c:\\bazarr\\bazarr\\subtitles\\tools\\embedded_subs_reader.py", line 120, in parse_video_metadata
    mediainfo_path = get_binary("mediainfo")
  File "c:\\bazarr\\bazarr\\utilities\\binaries.py", line 73, in get_binary
    raise BinaryNotFound
utilities.binaries.BinaryNotFound

In case it helps. I have already added the CLI version of MediaInfo to the PATH but it didn't work.
I have also installed MediaInfo to C:/Software/Mediainfo, and Program Files/MediaInfo as described in the code, but nothing happened.

**Comment by morpheus65535** [comment]
Both Discord and Wiki link are working perfectly fine. I've just tested them seconds ago.

Looks like an real issue with Windows. I'll look at it.

**Comment by Crazyhead90** [comment]
Since the work around / fix steps are missing:

1. Download the mediainfo CLI(!) version: https://mediaarea.net/en/MediaInfo/Download/Windows
2. Extract it anywhere and add the folder location to PATH
3. Verify if mediainfo is working in CMD by simply typing "mediainfo" (note you may have to re-open the cmd window)
4. If working: restart bazarr completely (not the restart option in the GUI, but actually closing the CMD window)
5. Change the option to mediainfo and it should be working now

**Comment by morpheus65535** [comment]
Thanks for leaving this for others!
