### ISSUE TITLE
Avoid re downloading a blacklisted subtitle by controlling if the dowloading candidate subtitle is actually, blacklisted 

### ISSUE THREAD

**Issue by bphd** [morpheus65535/bazarr#2040]
Making the control system better than just comparing URLs, but comparing the files themselves

And to avoid any mistake, as a security, not control only downloading candidate but downloaded ones too. Deleting them is they're part of the blacklist

**Comment by bphd** [comment]
And to avoid any mistake, as a security, not control only downloading candidate but downloaded ones too. Deleting them is they're part of the blacklist

**Comment by morpheus65535** [comment]
> Making the control system better than just comparing URLs, but comparing the files themselves

To compare something like the hash of the subtitles of the content of the file, it would require to download each and every potential results, hash it and compare the output to the one we've stored. That wont happen because it would add an unsolicited load to the provider.

> And to avoid any mistake, as a security, not control only downloading candidate but downloaded ones too. Deleting them is they're part of the blacklist

Subtitles file are deleted as soon as they are added to blacklist. There's no reason to scan all the existing subtitles on a schedule to delete blacklisted subtitles.

As discuss on Discord, I'm open to PR to improve the blacklist system. It's not a priority for me and, if you're not willing to work on this PR, it would be a feature request, not a bug.

Thanks for reporting.
