### ISSUE TITLE
upload put HI tag even when not selected

### ISSUE THREAD

**Issue by nodiaque** [morpheus65535/bazarr#2099]
**Describe the bug**
Select a series, click upload, select english langage, don't check HI. Subs get tagged as HI.

**Expected behavior**
Should be imported as selected on the GUI

**Screenshots**
![image](https://user-images.githubusercontent.com/324425/226152115-5513cb7e-d6ae-4fbc-a57e-4bad02bef719.png)
![image](https://user-images.githubusercontent.com/324425/226152125-fc130764-4d0e-4513-96ff-366ace6a9967.png)

**Software (please complete the following information):**
 - Bazarr: 1.2.0
 - OS: Unraid 6.11.5

**Comment by morpheus65535** [comment]
Bazarr will analyze every subtitles not tagged as HI to make sure they aren't. You're seems to include HI tags seeing how they got indexed. This is the expected behaviour.

**Comment by seraphx2** [comment]
I just want to get confirmation on this directly from you: Are you 100% sure it's doing it's job correctly? I came across a subtitle file uploaded by the admin of opensubtitles.org and it said NonHI in the filename (also had an HI specific file as well), but got listed as HI in bazaar. So since I'm not familiar with SRT stuff, I just want to be sure that there is a 100% reliable indicator that a file is HI enabled and the uploader was just mistaken and your software CANNOT be wrong?

**Comment by morpheus65535** [comment]
@seraphx2 This is the regex used to detect hearing-impaired content in subtitles file. You can test it by yourself and you'll see why Bazarr consider it as a HI subtitles:

`[*¶♫♪].{3,}[*¶♫♪]|[\[\(\{].{3,}[\]\)\}](?<!{\\an\d})`

Source: https://github.com/morpheus65535/bazarr/blob/master/bazarr/constants.py#L10
