### ISSUE TITLE
Sync and Download spike

### ISSUE THREAD

**Issue by dcglabs** [morpheus65535/bazarr#2183]
Latest version 1.2.2

I have noticed that it gets into a sync and download cycle for everything. Even if old subtitles were higher percentage. Huge spike in downloading subtitles. Started with the introduction of 1.2.2 a couple days ago. 
I have notice some titles getting repeat sync and download.
Others it replaces higher % subtitle - mostly because it is blowing out the API limits for opensubtitles 
![Screenshot from 2023-06-26 18-22-03](https://github.com/morpheus65535/bazarr/assets/5561155/66e5aa88-fc03-4d96-8cdf-4c0ba886bebf)
![Screenshot from 2023-06-26 17-42-29](https://github.com/morpheus65535/bazarr/assets/5561155/6e9720f3-54b9-41f0-b72c-b970f5a8cd95)
![Screenshot from 2023-06-26 18-19-05](https://github.com/morpheus65535/bazarr/assets/5561155/5fa4d70c-5361-4c76-a324-d499e493a475)

**Comment by vitiko98** [comment]
This problem was fixed some days ago. (Or I hope so)

![image](https://github.com/morpheus65535/bazarr/assets/59455966/c747ad35-814c-46b6-9bcd-a2f6a87c3bb7)

Maybe your Bazarr instance did not scan subtitles files from disk before searching for wanted subtitles. Try manually triggering `Update all Episode Subtitles from disk`, then wait and report your results.

**Comment by dcglabs** [comment]
That seems to be what was needed. The wanted bubble went down by 10k+ items. Thanks
