### ISSUE TITLE
Increased traffic to Google Analytics

### ISSUE THREAD

**Issue by kuba74656** [morpheus65535/bazarr#2187]
I am running into strange behaviour as the Bazarr instance on my server started doing 1700-2000 DNS requests per day to access google-analytics.com, yet I can't find a single mention of GA in any changelog from past couple of weeks.
This all started when my Bazarr updated to 1.2.2 prior to this version I didn't see any sort of this traffic.

Is this expected behaviour? Was GA added to Bazarr without mentioning it in the changelog?

**Comment by vitiko98** [comment]
Pleas see #2183

**Comment by morpheus65535** [comment]
Other than that, Google Analytics is being used since the early version of Bazarr. In 1.2.1, we've replaced Universal Analaytics with GA4 as the former has been deprecated on July 1st of this year: `Replaced deprecated Google Universal Analytics by GA4 [abc48b4](https://github.com/morpheus65535/bazarr/commit/abc48b4ed0fc9ba8daca16d0076c13b9d6be1475)`
