### ISSUE TITLE
TV Show episode search looking at wrong episode

### ISSUE THREAD

**Issue by gouthamravee** [morpheus65535/bazarr#2458]
**Describe the bug**
For the TV series community, every time I search for subtitles the season/episode is wrong. In most cases Bazarr searches for the pilot episode subs. 

**To Reproduce**
1. Do a manual search for subtitles on any episode in the TV show community

**Expected behavior**
Bazarr should detect the correct season and episode from sonarr, and then search for that episode's subtitles

**Screenshots**
![image](https://github.com/morpheus65535/bazarr/assets/31805744/75d73de1-d746-4fc7-8ff1-5aaa03e268e4)

**Software (please complete the following information):**
 - Bazarr: 1.4.2
 - Sonarr version 4.0.3.1486
 - OS: Docker on Debian Bookworm

**Comment by morpheus65535** [comment]
As you can see in the manual search modal, Sonarr is reporting "Community S01E01 Pilot" as scene name for this episode. Bazarr use the scene name when it's available to run search because it obviously the most trusted source of information. In that case, Sonarr is wrong. Simple fix: you can remove the series from Sonarr and add it back again. It will lost track of the scene name as it will not be aware that it's the one who downloaded it in the first place and Bazarr will use the filename since no scene name is provided by Sonarr.

**Comment by gouthamravee** [comment]
This is the first time in years I've seen "scene name" come up as a thing in sonarr. I'll have to look more into that and make sure its not affecting other series. 

Thank you! I believe this has solved the problem.
