### ISSUE TITLE
Permission denied if not owner

### ISSUE THREAD

**Issue by AnonymousX86** [morpheus65535/bazarr#2580]
**Describe the bug**
Bazarr can't save files if user is not owner of desired directory or directory is not protected (`chmod o=rwx`).

**To Reproduce**
1. Create user `bazarr` with group.
2. Create user `radarr` with group.
3. Add user `bazarr` to group `radarr`.
4. Change `/movies` directory ownership to `radarr:radarr`.
5. Apply permissions lesser than `o=rwx`, e.g. `0775`.
6. Run Bazarr with `PUID` and `PGID` of `bazarr`.
7. Bazarr can't save subtitles due to "Errno 13: permission denied".

**Expected behavior**
Bazarr should save subtitles, as it has sufficient permission to directory (`g=rwx`).

**Screenshots**
Shell output and logs below.

**Software**
 - Bazarr: 1.4.3 (from Linuxserver.io)
 - Radarr version: 5.6.0.8846 (from Linuxserver.io)
 - Sonarr version: 4.0.5.1710 (from Linuxserver.io)
 - OS: Ubuntu 22.04 LTS
 - Docker version: 27.0.3

**Additional context**
Example:
```sh
$ cd /movies
$ ls -l | grep Dune
drwxrwxr-x 2 radarr radarr 4096 Jun  1 01:29 Dune
$ ls -l Dune
total 2539684
-rwxrwxr-x 1 radarr radarr 2599600403 Jun  1 01:28 'Dune.mp4'
-rwxrwxr-x 1 radarr radarr     175894 May 26 12:09  fanart.jpg
-rwxrwxr-x 1 radarr radarr       8626 Jul 12 12:21  movie.nfo
-rwxrwxr-x 1 radarr radarr     837275 May 26 12:09  poster.jpg
$ groups bazarr
bazarr : bazarr sonarr radarr
```
Docker logs:
```py
15 23:34:16,679 - root                             (7fd7b968bb38) :  ERROR (download:99) - BAZARR Error saving Subtitles file to disk for this file /movies/Dune/Dune.mp4: PermissionError(13, 'Permission denied')
```
Issue does not occur when applying `o=rwx` permissions. Subtitles are being saved with `bazarr:bazarr` ownership with `644` permissions.
```sh
$ ls -la
drwxrwxrwx 1 sonarr sonarr     12288 Jul 15 21:55 .
-rw-r--r-- 1 bazarr bazarr     22448 Jul 15 21:55 Dune.srt
```

**Comment by TheAmitMa** [comment]
I’m dealing with the same issue

**Comment by morpheus65535** [comment]
Could you please enable debug log, reproduce the issue and provide the log file?

**Comment by morpheus65535** [comment]
No news, good news!

**Comment by debling** [comment]
I was having the same issue, both directories and files are under owner `sonarr`, and group `media`, where the users sonarr and bazarr are under this group.

The issue arrived because Sonarr created the directories with write permissions only to the owner, so I fixed it by going into Sonarr media management settings. Enabling the advanced options will show the file permissions options, changing the `chmod folder` option to 775 (write permissions to owner and group, read permissions to all) fixed the issue.

<img width="1048" height="638" alt="Image" src="https://github.com/user-attachments/assets/2150a354-6a71-4a2e-8488-45fd4653d8e4" />

This only changes for future content, to fix the current directories you will need to run `chmod g+w <media directory>` to fix it.




This was the error I was seeing the logs of bazarr before applying the fix:

```python
Traceback (most recent call last):

  File "/nix/store/cka2qpxz244cy7j8q3zgmgzki7ykkaq8-bazarr-1.5.6/share/bazarr/bazarr/../bazarr/subtitles/download.py", line 109, in generate_subtitles

    saved_subtitles = save_subtitles(video.original_path, subtitles,

                                     single=settings.general.single_language,

    ...<4 lines>...

                                     path_decoder=force_unicode

                                     )

  File "/nix/store/cka2qpxz244cy7j8q3zgmgzki7ykkaq8-bazarr-1.5.6/share/bazarr/bazarr/../custom_libs/subliminal_patch/core.py", line 1246, in save_subtitles

    with open(subtitle_path, \'wb\') as f:

         ~~~~^^^^^^^^^^^^^^^^^^^^^

PermissionError: [Errno 13] Permission denied: \'/srv/media/tv/Servant/Season 3/Servant.S03e10.pt-BR.srt\
```

I'm using bazarr v1.5.6, running as a systemd service under nixos, using the module provided by nixpkgs.
