### ISSUE TITLE
Fix Uppercase produces lowercase i's

### ISSUE THREAD

**Issue by golonac** [morpheus65535/bazarr#2622]
**Describe the bug**
Tiny bug - with all Sub-Zero Modifications enabled, if a subtitle is in all caps, the Fix Uppercase mod seems to produce lowercase i's. The Common Fixes mod seems to have a fix to capitalize lowercase i's, but maybe it's run before Fix Uppercase as it has a lower order value?

**To Reproduce**
Process an all-caps subtitle with "I" present and all Sub-Zero mods enabled.

**Expected behavior**
Get an uppercase "I".

**Software (please complete the following information):**
 - Bazarr: v 1.4.3
 - Radarr version v 5.8.3.933
 - OS: Windows 11

**Comment by morpheus65535** [comment]
Just to be sure we understand each other, can you wrote the original sentence and the expected one so I can properly test? Thanks!

**Comment by golonac** [comment]
Original: `BUT, LUCKILY, I HAD A PLAN.`
Expected: `But, luckily, I had a plan.`
Actual: `But, luckily, i had a plan.`

**Comment by morpheus65535** [comment]
Sorry for the delay. Can you provide the original subtitles file please? I really want to fix that one.

**Comment by morpheus65535** [comment]
So, looking at it again, I realize that it's the expected behaviour since this mods use the capitalize() function of Python strings. It convert the whole string to lower case and capitalize the first letter if it's alphabetic character. There's no grammatical engine underneath it to make sure that words that typically starts with a capital letter in a specific language keep it (ex.: I, February, Jonathan in English.).

There's not much I can do here without implementing some grammatical engine that can help with this. If you have some idea on how to achieve this, I'm open to review a PR! :-)
