### ISSUE TITLE
v1.4.4-beta.31 - Subs not showing from Subdl ( available on the site ) 

### ISSUE THREAD

**Issue by alfuraiji** [morpheus65535/bazarr#2625]
**Describe the bug**
The first issue was that Bazarr downloaded the sub automatically and I got notified .. Checked the episode but the subfile is missing !!! further investigation and by manually searching the subtitle for the same episode but nothing showing in Bazarr search results ( Tested with One Piece ) 

**Screenshots**
https://imgur.com/a/589OXjm

**Software (please complete the following information):**
 - Bazarr: [v1.4.4-beta.31]

[bazarr.log](https://github.com/user-attachments/files/16648168/bazarr.log)

**Comment by morpheus65535** [comment]
Please provide the link to the subtitles page.

**Comment by alfuraiji** [comment]
https://subdl.com/subtitle/sd1300008/one-piece/twenty-second-season

all 1116 subtitles not appearing

**Comment by alfuraiji** [comment]
Subdl is very critical for Arabic subtitles and I think it's the only one with huge Arabic translator ( Subscene migrants ) 
And I'm only using Bazarr for Arabic subs.

**Comment by morpheus65535** [comment]
Subdl API return no episode numbers at all for most of this series subtitles. There's not much I can do with that.

You're right, subdl provider haven't implemented absolute numbering because they simply doesn't support it through their API.

Keep in mind that their API doesn't allow Bazarr to list all subtitles. Season packs or non text based subtitles are excluded.

TBH, they still have a lot of bugs and they take their time to fix them...

**Comment by alfuraiji** [comment]
Alright thanks for the clarification 
I'm available if you need any testing in the future.

**Comment by h1i0a** [comment]
soo is there any fix or not he is the only site that have arabic for tv series for only murders in the building
