### ISSUE TITLE
Since last update, translating subs takes ages!

### ISSUE THREAD

**Issue by FiyiK** [morpheus65535/bazarr#2678]
Normally translating subs were rapidly done by bazarr, last week it started translating very slow. One sub translates in like a few minutes

Behavior:
1. Go to serie name
2. Download English subtitle for each episode
3. Click on mass edit, select all and translate to any language
4. It takes hours for a serie with just one or two seasons to translate subs from English to any other language
5. Next to that, it doesn't even translate from English to any language because of malfide subtitle (it's the embedded one). Still this issue persists for months

Expected behavior
Translate any sub, rapidly fast! Translating should cost a few seconds to 10 seconds max. Can this be fixed?

 - Bazarr: 1.4.4.
 - Radarr version 5.10.4.9218
 - Sonarr version 3.0.10.1567
 - OS: Windows 11

**Comment by morpheus65535** [comment]
Not really the better approche to get something fixed with an open source project where the contributor do it out of kindness for the community.

Bazarr is relying on Google Translate web interface that as changed over the last months and has been causing issues. In a desperate attempt, we choose to switch from a massive send of subtitles sentences in a single request to a one sentence at a time. It takes far more time but it's been working fine during the test we've done.

Maybe if you provide a debug log while reproducing the issue, we'll be able to see what's wrong.

**Comment by FiyiK** [comment]
Who says i dont appreciate the kindness? I donated you as a result of appreciation before. I don't get it, i am reporting an issue and asking for a fix. Nothing wrong with it. If you don't like the approach, then just don't help. Thanks for all your efforts, delete the post.
