### ISSUE TITLE
 Subdivx Provider Error 520

### ISSUE THREAD

**Issue by Ph1L82** [morpheus65535/bazarr#2698]
**Describe the bug**
Can't search neither download subtitles directly from subdivx, Subdivx provider not working.

**To Reproduce**
(Having suibdivx configured as provider)
1. Go to a show or movie.
2. Click on search
3. Go to System > Logs
4. Click on filter, and on include write "subdivx"
5. should see the errors:
2024-10-06 13:11:38|INFO    |root                            |Throttling 
 for 10 minutes, until 24/10/06 13:21, because of: HTTPError. Exception info: "'520 Server Error:  for url: https://www.subdivx.com/inc/ajax.php' ~ subdivx.py@198"|
2024-10-06 13:12:16|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
2024-10-06 13:21:40|INFO    |root                            |Using subdivx again after 10 minutes, (disabled because: HTTPError)|

**Expected behavior**
Should search the selected title's subtitle and properly donwload it, rename it, etc.

**Software (please complete the following information):**
 - Bazarr: 1.4.5
 - Radarr version 5.8.3.8933
 - Sonarr version 4.0.8.1874
 - OS: Linux-6.8.12-1-pve-x86_64-with-glibc2.36
 - Python Version: 3.11.2

**Additional context**
Subdivx is the biggest source of spanish subtitles for tv shows and movies there is (as fas as I know), so it's important that this one provider works.

**Comment by morpheus65535** [comment]
This is a server error on their side, there's nothing to fix here. Cloudflare return a 520 because subdivx isn't responding properly.

https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#error-520-web-server-returns-an-unknown-error

The provider get throttled since there's no benefit in hammering an unstable provider.
