### ISSUE TITLE
[Feature Request] Manual import of subtitles

### ISSUE THREAD

**Issue by xfouloux** [morpheus65535/bazarr#331]
Hi,

would it be possible to add the capability to upload subtitles manually for an episode, or a complete season ?
Bazarr would then handle the renaming of the subtitle to match the episode name

Maybe a bit like Lidarr does by matching tracks for season upload if file match does not succeed.

Thanks

**Comment by sotiris-bos** [comment]
+100 for this. When I am away and me or a friend wants to watch something, it is a pain adding subtitles when all other options are exhausted.

Having bazarr on the open internet through a reverse proxy (ideally organizr 2 for authentication) and the ability to manually add subtitles instead of having to vpn to the machine and scp or samba copy subtitles would be so very helpful.

**Comment by morpheus65535** [comment]
Now in dev branch with #512 .
