### ISSUE TITLE
Support for movie subtitles in combination with Radarr

### ISSUE THREAD

**Issue by thyeestes** [morpheus65535/bazarr#42]
Would it be possible to add support for Radarr as well? To download movie subtitles.

**Comment by morpheus65535** [comment]
I've think about it and it's been requested a couple of times but I don't plan to implement this:

- Subtitles for movies are a one time deal: you don't need to check, like series, each time a new episode is available.
- The guys at Radarr have already planned this feature. Those at Sonarr don't plan to implement this. That's why I created Bazarr.

**Comment by morpheus65535** [comment]
Maybe someday if the guys at Radarr don't implement it.

**Comment by thyeestes** [comment]
Okay clear. Thanks I'll keep watching the progress.
