### ISSUE TITLE
Auto-search after new content is added

### ISSUE THREAD

**Issue by GeoCookie** [morpheus65535/bazarr#426]
Thanks again @morpheus65535 for the auto-search function (#308), it is a great improvement!

From what I understood, Bazarr search subtitles when new content is detected, with a limitation to five items max to avoid longer scan. So I guess these scans runs simultaneously.

Can we imagine this scenario?
Bazarr look up for new content. Each new content found is added to a temporary list. Once the content scan ended, Bazarr looks up for subtitles based on the temporary list. This way, subtitle task will not extend content task duration and the limitation of five items can be removed. This could be completed with the ability to launch content scan from Radarr/Sonarr after a download completion. This way, maybe we can reduce planned scan frequency. It will reduce the Bazarr’s workload.

I hope I did not say too much nonsense since I don’t how Bazarr works

**Comment by morpheus65535** [comment]
We've looked into listening to the signalR feed from Sonarr and Radarr to be able to reduce scan frequency but it's not possible at the moment due to a limitation of mono 5.2 on which they rely on Linux. We'll see if we can do better once mono is going to be able to manage websocket connection for signalR.

Until then, the 5 items limit have to be kept this way. What you propose would require a refactoring of the whole synchronization process and we don't want to to that since we want to go the signalR way in time.

Thanks for the suggestion!

**Comment by GeoCookie** [comment]
Thank you for your quick reply. Wait and see :)
