### ISSUE TITLE
After configuring Bazarr the URL doesn't work

### ISSUE THREAD

**Issue by silveringking** [morpheus65535/bazarr#456]
I did a docker install of Bazarr, for some reason after me configuring bazarr and reboot the server it doesn't work.

Here is a screenshot.

https://imgur.com/fkF8Mj2

Kind regards

**Comment by morpheus65535** [comment]
I guess you're nto using the proper base_url, Did you try to use only the IP to access it without anything after that?

**Comment by silveringking** [comment]
I used http://51.xx.xxx.xxx:6767

And

http://51.xx.xxx.xxx:6767/bazarr

And 

http://51.xx.xxx.xxx:6767/bazarr/

What is the proper url?

**Comment by morpheus65535** [comment]
Please provide your config.ini file and scramble confidential information.

**Comment by silveringking** [comment]
Here is the config.ini (the ips were removed but were the same, the api keys were different).
```

[assrt]
token =

[sonarr]
apikey = [removed]
full_update = Daily
ip = 51.[removed]
only_monitored = False
base_url =
ssl = False
port = 8989

[radarr]
apikey = ff21651d45784877a0998cf1a69403b2
full_update = Daily
ip = 51.[removed
only_monitored = False
base_url =
ssl = False
```

**Comment by morpheus65535** [comment]
Is that the complete file? If it is, it is clearly incomplete and I suggest you delete it and reconfigure Bazarr.

**Comment by silveringking** [comment]
How do I reconfigure bazarr then?

**Comment by silveringking** [comment]
Sorry there was a mistake I didn't copy the whole file:

[assrt]
token = 

[sonarr]
apikey = [edited]
full_update = Daily
ip = 51.[edited]
only_monitored = False
base_url = 
ssl = False
port = 8989

[radarr]
apikey = [edited]
full_update = Daily
ip = 51.[edited]
only_monitored = False
base_url = 
ssl = False
port = 7878

[anticaptcha]
anti_captcha_key = 

[auth]
username = 
password = 
type = None

[general]
movie_default_hi = False
minimum_score = 90
ip = 0.0.0.0
use_sonarr = True
serie_default_language = ['pt', 'vi']
chmod = 0640
path_mappings_movie = [['', ''], ['', ''], ['', ''], ['', ''], ['', '']]
use_scenename = True
subfolder_custom = 
use_postprocessing = False
enabled_providers = legendastv,opensubtitles,podnapisi,subscene,subscenter,supersubtitles,tvsubtitles
serie_default_enabled = True
port = 6767
ignore_pgs_subs = False
movie_default_language = ['pt', 'vi']
days_to_upgrade_subs = None
movie_default_enabled = True
use_radarr = True
path_mappings = [['', ''], ['', ''], ['', ''], ['', ''], ['', '']]
upgrade_subs = False
subfolder = current
base_url = 51.[edited]/
page_size = 25
chmod_enabled = False
auto_update = True
throtteled_providers = {}
upgrade_manual = False
postprocessing_cmd = 
minimum_score_movie = 70
branch = master
serie_default_hi = False
debug = False
anti_captcha_provider = None
single_language = False
multithreading = True
use_embedded_subs = True
adaptive_searching = False

[addic7ed]
username = 
password = 
random_agents = True

[proxy]
username = 
url = 
exclude = localhost,127.0.0.1
password = 
type = None
port = 

[xsubs]
username = 
password = 

[legendastv]
username = silveringking
password = [edited]

[opensubtitles]
username = silveringking
use_tag_search = False
skip_wrong_fps = False
ssl = False
vip = False
timeout = 15
password = [edited]

[deathbycaptcha]
username = 
password =

**Comment by morpheus65535** [comment]
Delete base_url line in [general] and restart Bazarr. Go to settings, save settings and restart Bazarr again. You should be ok after that.

**Comment by morpheus65535** [comment]
Can I close this issue?

**Comment by 4C3T** [comment]
Hmm... Just got an error in Firefox, an 404 I believe. First I thought I'd have a check here to see if that was connected to an update.

So, I did a check in the bazarr directory and made a weird discovery!
My config.ini has a filesize of 2,07 kB, but it's completely blank inside!

Does this happen if the computer isn't shut down properly? Had to shut down due to lightning and I couldn't wait for it to shut down entirely and yanked the cable, just in the nick of time. A couple of seconds later a bolt struck a transformer station (or something) and the whole neighborhood went dark.

I know stuff like this can happen if files are opened, but I find it weird that a config file is left opened for write access. Isn't this something that should've been done if something is about to change (settings)?

I'm about to go fishing to see if I can find a backup copy somewhere on my drives. Seems that I need to start including the whole suit in my daily backups, which I seem to have forgotten.

**Comment by morpheus65535** [comment]
@4C3T I have no idea. Never seen that before.
