### ISSUE TITLE
Multilingual subtitle download

### ISSUE THREAD

**Issue by zpengcom** [morpheus65535/bazarr#468]
Only one language subtitle can now be downloaded,。
I hope want to download bilingual subtitles or multiple language subtitles.

--Bad English language expression--

**Comment by morpheus65535** [comment]
Please fill out this form:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.6.1]
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: [e.g. Windows 10]

**Additional context**
Add any other context about the problem here.

**Comment by morpheus65535** [comment]
Disable single language mode and you'll be able to download as much language as you want.
