### ISSUE TITLE
Bazarr won't start as non-root user.

### ISSUE THREAD

**Issue by deepwather** [morpheus65535/bazarr#501]
**Describe the bug**
Bazarr won't start as non-root user. 

**To Reproduce**
```
# cd /tmp/
# wget https://github.com/morpheus65535/bazarr/archive/v0.7.5.1.tar.gz
# tar -xvf v0.7.5.1.tar.gz

# mkdir /opt/radarr
# useradd --system --home-dir=/opt/bazarr bazarr
# usermod -a -G usenetserver bazarr
# cp -R bazarr-0.7.5.1/* /opt/bazarr/
# ls -la /opt/bazarr/
# chown -R bazarr:usenetserver /opt/bazarr/
# yum install python-pip
# pip install -r /opt/bazarr/requirements.txt

# su bazarr
# /usr/bin/python /opt/bazarr/bazarr.py
```

**Expected behavior**
Bazarr should start under user "bazarr".

**Actual begavior**
Following Error is happening:
```
bash-4.2$ /usr/bin/python /opt/bazarr/bazarr.py
Bazarr starting...
Traceback (most recent call last):
  File "/opt/bazarr/bazarr/main.py", line 23, in <module>
    from init import *
  File "/opt/bazarr/bazarr/init.py", line 7, in <module>
    import rarfile
  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2950, in <module>
    _check_unrar_tool()
  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2931, in _check_unrar_tool
    custom_check([ORIG_UNRAR_TOOL], True)
  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2823, in custom_check
    p = custom_popen(cmd)
  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2813, in custom_popen
    creationflags=creationflags)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

```

**Software (please complete the following information):**
 - Bazarr: [v0.7.5.1]
 - Radarr version [latest]
 - Sonarr version [latest]
 - OS: [CentOS 7.6]

**Additional context**

**Comment by morpheus65535** [comment]
Bazarr is unable to run unrar. You need to fix permission on your side. That's not a Bazarr issue.

**Comment by deepwather** [comment]
Ok thank you.
Do you have any idea, why it's not working out of the box? Because all files in the "Bazarr" folder are owned by bazarr. Maybe itz an SELinux Issue? There are as well all needed steps done, described by you in your wiki
Cheers

**Comment by morpheus65535** [comment]
To be honest, no. Maybe it's related to SELinux as you said. If unrar is installed, we use it but if we run into an access denied issue trying to, it fail.

**Comment by Shnoobins** [comment]
No to resurrect an old thread, but I had a similar issue. @deepwather not sure if you got yours working with another user but this maybe helpful. 

I don't have unrar installed otherwise. HOWEVER, I see unrar is included with bazarr: 

`[root@localhost ~]# find / | grep -i unrar
/apps/bazarr/bin/Linux/aarch64/UnRAR
/apps/bazarr/bin/Linux/aarch64/UnRAR/unrar
/apps/bazarr/bin/Linux/armv5tel/UnRAR
/apps/bazarr/bin/Linux/armv5tel/UnRAR/unrar
/apps/bazarr/bin/Linux/i386/UnRAR
/apps/bazarr/bin/Linux/i386/UnRAR/unrar
/apps/bazarr/bin/Linux/x86_64/UnRAR
/apps/bazarr/bin/Linux/x86_64/UnRAR/unrar
/apps/bazarr/bin/MacOSX/i386/UnRAR
/apps/bazarr/bin/MacOSX/i386/UnRAR/unrar
/apps/bazarr/bin/Windows/i386/UnRAR
/apps/bazarr/bin/Windows/i386/UnRAR/UnRAR.exe
/apps/bazarr/bin/Windows/i386/UnRAR/license.txt`

and it seems to have the correct permissions, as it lives in the same folder as the rest of the install, and has permissions from the user in question: 

`[root@localhost ~]# ll /apps/bazarr/bin/Linux/x86_64/UnRAR/unrar
-rwxr-xr-x. 1 bazarr bazarr 307352 Sep 29 12:37 /apps/bazarr/bin/Linux/x86_64/UnRAR/unrar`

I am not certain what is being called when running as root, but looking at that stack trace, it seems the unrar program is set in the <install dir>/libs/rarfile.py file, in my case is in /apps/bazarr/libs/rarfile.py

I modified the file on line 55 and 191 to have the full path to the unrar included in bazarr. To be clear, that means I set: 

51: rarfile.UNRAR_TOOL = /apps/bazarr/bin/Linux/x86_64/UnRAR/unrar
191: UNRAR_TOOL = /apps/bazarr/bin/Linux/x86_64/UnRAR/unrar

After this change, the app started as expected. @morpheus65535 do you think its possible to have this set to the install path or something instead of just being set to 'unrar' as it is currently to avoid a similar situation for people who do not want to run as root? Or have I made a grave mistake here? I hope I have provided enough detail for you.

**Comment by morpheus65535** [comment]
@Shnoobins We use `which` to find an available `unrar` executable. You need to have execute permission on it or it will fail. You have to manage this on your own. When we don't find an `unrar` executable, we try to use those included in Bazarr's bin directory. Again, it's up to you to manage permission on your Linux machine. We won't do dirty patch to Bazarr to fit your curious use case.

**Comment by Shnoobins** [comment]
If by "curious case" you mean "default installed CentOS 7 install" sure. 

The which command succeeds from both users. While I understand you may not want to hard code it that way, the workaround I noted above is just that...a workaround. 

`[root@localhost ~]# which unrar
/usr/bin/which: no unrar in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
[root@localhost ~]# su bazarr
[bazarr@localhost root]$ which unrar
/usr/bin/which: no unrar in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
`

As I noted previously, the permissions on the bazarr unrar files have execute permissions on them for all users. It seems unnecessary to give them write permissions as well. As you yourself noted "You need to have execute permission on it or it will fail." 

It seems to be failing even with the proper permissions.

**Comment by morpheus65535** [comment]
Sorry, "curious case" wasn't the proper way to describe this. Whoever, I believe there's something wrong with your permissions as it is working on my setup. The code in Bazarr is working fine as over 5000 subtitles have been unrared only yesterday. If the Bazarr user have proper access to the unrar executable, it can use it. If not, it's because there's something to adjust on the permission side.

**Comment by Shnoobins** [comment]
Does the unrar command rely at all on python or the version installed? Until recently, it was working fine, however the most recent update (or I assume it was that update) started checking for version of python. I did not realize I had compiled a newer python version but was not actually using it. I went through the process today to get it completed recompiled with 2.7.16 and the systemd file pointed to the correct version of python. I don't see why or how, but this is the only change otherwise.

**Comment by morpheus65535** [comment]
Yes we add to enforce the Python version check because we were supporting a lot of people using Python version older than 5 years and taking us so much time.

Can you confirm that using a previous version is fixing your issue? If not, I suggest you open a new issue referring to this one so we don't spam the OP with your issue.
