### ISSUE TITLE
Not Downloading Subtitles - Error trying to get video information for this file

### ISSUE THREAD

**Issue by zytoc** [morpheus65535/bazarr#619]
**Describe the bug**
A subtitle will be downloading infrequently.  Most of the time there are no subtitles downloaded.  I'm getting this message in logs:
"BAZARR Error trying to get video information for this file: /tv/How It's Made/Season 15/How It's Made - S15E13 - Leather Wallets; French Horns; Soy Sauce; Children's Ride-On Cars.mkv"

When I click on the log entry it brings up this stack trace:
"Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_subtitle.py", line 70, in get_video
  refine_from_ffprobe(original_path, video)
 File "/app/bazarr/bazarr/get_subtitle.py", line 951, in refine_from_ffprobe
  data = parser.parseFfprobe(path)
 File "/app/bazarr/bazarr/../libs/pyprobe/pyprobe.py", line 39, in parseFfprobe
  self._checkExecutable(self._ffprobe)
 File "/app/bazarr/bazarr/../libs/pyprobe/pyprobe.py", line 202, in _checkExecutable
  stderr=subprocess.STDOUT
 File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
  raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command \[\/usr/bin/ffprobe\, \--help\]\ returned non-zero exit status -11"

This is happening on nearly all the tv episodes I have, almost all of which have the series name, season and episode number, and title in their file name.

**To Reproduce**
1. Request this episode with this filename be used to download it's subtitle
2. Go to logs, and view errors
3. Check if this error or a similar one is created.

**Expected behavior**
The subtitles for the episode should be downloaded.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 0.81
 - Radarr version 0.2.0.1358
 - Sonarr version 2.0.0.5338
 - OS: Debian Buster (in docker container - image from linuxserver.io)
 - Kernel: Linux generic 5.1.1

![image](https://user-images.githubusercontent.com/56322388/66432026-66e5f680-e9da-11e9-8c8c-6d61d15a8645.png)

**Additional context**
Some other file names that are having the same issue:
- "BAZARR Error trying to get video information for this file: /tv/Guy's Grocery Games/Season 1/Guy's Grocery Games - S01E10 - Game Day Rush.mp4"

- "BAZARR Error trying to get video information for this file: /tv/Property Brothers/Season 7/Property Brothers - S07E06 - Entertaining in Style.mkv"

I have Addic7ed, OpenSubtitles (VIP), Podnapisi, Subscenter and TVSubtitles as providers.  I also have an anti-captcha provider.

**Comment by morpheus65535** [comment]
Can you try to uninstall `/usr/bin/ffprobe` and try again? Look like your version of ffprobe is returning -11 which is segmentation fault.

**Comment by zytoc** [comment]
Thank you for your quick response!

I have Proxmox (debian based) with an LXC container running docker images for Sonarr, Radarr, Bazarr...etc.

/usr/bin/ffprobe is not found in the LXC container or the host, but it is found in the docker container.  I'm new-ish to servers and Linux in general so I couldn't find a command that worked to remove /usr/bin/ffprobe from the container as apt-get was not found in the container.  I don't know but I would assume just removing that entry is the wrong way to do that.

Any help would be greatly appreciated.


PS: I found that there is one more different stack trace littered throughout the errors:
![image](https://user-images.githubusercontent.com/56322388/66434630-2ee1b200-e9e0-11e9-94a8-85d0c9530ba0.png)

**Comment by morpheus65535** [comment]
What docker image are you using? We only support `linuxserver/bazarr` and it doesn't contain ffprobe.

**Comment by zytoc** [comment]
I'm using Linuxserver/bazarr image from about a month ago.

**Docker Image List:**
![image](https://user-images.githubusercontent.com/56322388/66435124-5b49fe00-e9e1-11e9-949b-bef14c9e87c1.png)

**Docker Container List**
![image](https://user-images.githubusercontent.com/56322388/66435381-edea9d00-e9e1-11e9-84ed-960b304efdde.png)

ffprobe is listed under /usr/bin
![image](https://user-images.githubusercontent.com/56322388/66435221-9a784f00-e9e1-11e9-9c35-edd2a438ae36.png)

Not sure why it would be there if it isn't in the image originally.  Maybe I should pull the newest image and see if there is a discrepancy?

**Comment by morpheus65535** [comment]
You are right, my bad. ffmpeg is included for some time but it works fine for me. Can you try `linuxserver/bazarr:development`?

**Comment by morpheus65535** [comment]
Are you still having this issue?

**Comment by Zeusy123** [comment]
I have update my  docker to your latest development version and im getting same problems cant read information from ANY video file:(   ive checked multiple vidfeo files and they play fine and ffprobe reads them fine.

Its as if bazarr cant find ffprobe????

**Comment by morpheus65535** [comment]
@Zeusy123 can you run `/usr/bin/ffprobe` inside the runnign container?

**Comment by zytoc** [comment]
This issue hasn't been resolved by running development version of the
docker image.  Sorry, life got busy for a bit there.  I don't mean to keep
an issue stale.

**Comment by draeven** [comment]
REOPEN :D

**Comment by morpheus65535** [comment]
@draeven that's necromancy after more than a year. Open a new issue with everything required ans we'll look into it.

**Comment by cooperdk** [comment]
Reopen an issue that hasn't been fixed or even addressed? 8|

I am having the exact same issue btw, running on Windows newest dev version, and with the included ffmpeg/ffprobe binaries copied both to root and to the windows folder.


BAZARR FFprobe was unable to find audio tracks in the file! | a few seconds ago
-- | --
  | BAZARR FFprobe was unable to find video tracks in the file! | a few seconds ago
  | FFprobe found: {} | a few seconds ago
  | BAZARR FFprobe used is c:\windows\ffprobe.EXE | a few seconds ago
  | Computed hashes {'opensubtitles': '25313e54433d52f6'}

**Comment by morpheus65535** [comment]
> Reopen an issue that hasn't been fixed or even addressed? 8|
> 
> I am having the exact same issue btw, running on Windows newest dev version, and with the included ffmpeg/ffprobe binaries copied both to root and to the windows folder.
> 
> BAZARR FFprobe was unable to find audio tracks in the file! | a few seconds ago
> 
> * | -
>   BAZARR FFprobe was unable to find video tracks in the file! | a few seconds ago
>   FFprobe found: {} | a few seconds ago
>   BAZARR FFprobe used is c:\windows\ffprobe.EXE | a few seconds ago
>   Computed hashes {'opensubtitles': '25313e54433d52f6'} | a few seconds ago

don't copy ffprobe everywhere, it's already included in Bazarr source and have the required version. Don't install yours.

**Comment by cooperdk** [comment]
I just added a bit of stuff above, ffprobe is copied from your distro to c:\windows and bazarr finds it there - even though it is where it should be, in X:\Bazarr\bin\Windows\i386\ffmpeg\ffprobe.exe
as well as in C:\Bazarr\bin\Windows\i386\ffprobe\ffprobe.exe

Do you want me to add a new issue?

Also, most of the subtitle providers error out now, both on my Synology and on Windows (where I installed a test version).
I tried your latest development because you advised someone else to do that due to addic7ed timeout, but that is not enough to make it work.


Name | Status | Next Retry
-- | -- | --
addic7ed | ConnectTimeout | in 43 minutes
bsplayer | Exception | in 10 minutes
opensubtitles | DownloadLimitReached | in 6 hours
podnapisi | Good | -
subscene | TypeError | in 3 minutes
subscenter | Good | -
supersubtitles | Good | -
tvsubtitles | BadZipFile | in 4 minutes
yifysubtitles | Good | -

**Comment by morpheus65535** [comment]
That's a support request, not an issue. Come to Discord for support.

**Comment by cooperdk** [comment]
I will, but I find it is a bug as it seems that no series provider actually find anything. Didn't anyone else mention it? I had no trouble until recently.

Also, this is on two platforms (Win and aarch64) ... however yesterday, it worked at some point but then it stopped.

And, manual searches actually work. This happens when the auto subtitle search (or a recursive search as far as I remember) is started.

**Comment by morpheus65535** [comment]
> I will, but I find it is a bug as it seems that no series provider actually find anything. Didn't anyone else mention it? I had no trouble until recently.
> 
> Also, this is on two platforms (Win and aarch64) ... however yesterday, it worked at some point but then it stopped.
> 
> And, manual searches actually work. This happens when the auto subtitle search (or a recursive search as far as I remember) is started.

In the last 7 days, about 15 000 users have been able to download almost 2 000 000 subtitles from 40 different providers. I'm pretty sure Bazarr is working perfectly fine and you have something wrong in your setup. Seeing that you're fiddling with stuff without understanding the consequences, I'm not that surprise that your setup could be broken.

**Comment by cooperdk** [comment]
On my NAS running on an ARM, it is completely standard.

I haven't changed a bit in the code at all. All I have done is to copy the ff programs to c:\windows and I actually think I did that because I had read somewhere that it might be necessary.
If the app was coded to use the internal binaries, it wouldn't look elsewhere.
Also, as mentioned, the binaries work perfectly fine outside of Bazarr, both from the runtime directory and from the windows folder, and with the user set up to run bazarr.

The only stuff I tried to change is adaptive and threaded searching, which makes no difference.

But I can try to start a Debian VM from scratch and/or your Docker image and compare the results.

**Comment by morpheus65535** [comment]
@cooperdk as suggested come to Discord and the support team will try to help you.

**Comment by cooperdk** [comment]
I am jumping in soon... I just wanted to try the docker first 👍

**Comment by cooperdk** [comment]
Never mind this. The issue for me was that there were no subtitles in my defined language. The script probably fired too fast, causing the providers to throttle my IP (I guess)

**Comment by kavemang** [comment]
Hi, sorry if this is the wrong place, I've added bazarr to my media server stack and am also getting this issue. Just finished confirming my volume paths and can see that bazarr sees the files themselves (I think?) since it's showing me the episodes on its end. 

error examples from log: 

`Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 6884, in get

    return clone.execute(database)[0]

  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 4275, in __getitem__

    return self.row_cache[item]

IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/get_subtitle.py", line 77, in get_video

    refine_from_ffprobe(original_path, video)

  File "/app/bazarr/bin/bazarr/get_subtitle.py", line 1338, in refine_from_ffprobe

    file_id = TableEpisodes.select(TableEpisodes.episode_file_id, TableEpisodes.file_size)\\

  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 6887, in get

    raise self.model.DoesNotExist(\'%s instance matching query does \'

database.TableEpisodesDoesNotExist: <Model: TableEpisodes> instance matching query does not exist:

SQL: SELECT "t1"."episode_file_id", "t1"."file_size" FROM "table_episodes" AS "t1" WHERE ("t1"."path" = ?) LIMIT ? OFFSET ?

Params: [\'/media/The Expanse/Season 5/The Expanse - S05E01 - Exodus WEBDL-2160p Proper.mkv\', 1, 0]`


`Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 6884, in get

    return clone.execute(database)[0]

  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 4275, in __getitem__

    return self.row_cache[item]

IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/get_subtitle.py", line 77, in get_video

    refine_from_ffprobe(original_path, video)

  File "/app/bazarr/bin/bazarr/get_subtitle.py", line 1338, in refine_from_ffprobe

    file_id = TableEpisodes.select(TableEpisodes.episode_file_id, TableEpisodes.file_size)\\

  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 6887, in get

    raise self.model.DoesNotExist(\'%s instance matching query does \'

database.TableEpisodesDoesNotExist: <Model: TableEpisodes> instance matching query does not exist:

SQL: SELECT "t1"."episode_file_id", "t1"."file_size" FROM "table_episodes" AS "t1" WHERE ("t1"."path" = ?) LIMIT ? OFFSET ?

Params: [\'/media/Alice in Borderland (2020)/Season 1/S01E01.mkv\', 1, 0]`
