### ISSUE TITLE
subtitles shifted by one episode

### ISSUE THREAD

**Issue by soldier999** [morpheus65535/bazarr#643]
For one entire season, all the subtitles are shifted by one episode, for example, the subtitles for Season 3 episode 2 are wrong, but are correct for episode one. Subtitles downloaded for episode 3 are actually meant for episode 2.  Is there an easy fix for this?  The show itself is Big Mouth.
Software :
 - Sonarr version 2.0.0.5338 
 - OS: Linux Ubuntu 18.04.3

**Comment by morpheus65535** [comment]
You are probably renaming your episode?

**Comment by soldier999** [comment]
Sonarr handles the renaming.

**Comment by morpheus65535** [comment]
I'm going to need a debug log where you reproduce the behaviour.

**Comment by soldier999** [comment]
In an attempt to do so, I turned on debugging, and redownloaded one of the shifted files but I can't find the show name in the debug file.

**Comment by morpheus65535** [comment]
Could you provide that debug log please?

**Comment by subtitlecat** [comment]
if you are looking for the current version of [YIFY Subtitles](https://subtitlecat.online/) then you can visit by clicking on the link

**Comment by dimitrov-adrian** [comment]
I also notice such behaviour but it's not related to sonarr or bazarr, it's about the video and subtitle file namings. It usually happens when first episode is named Showname.ep01-02 or something where the first two episodes are merged, and the subtitle for them are with same name, but then the episode is 03 and subtitles are 02

**Comment by soldier999** [comment]
Thanks I'll look into it.
