### ISSUE TITLE
[RFI] Force bazarr to upgrade all subtitles

### ISSUE THREAD

**Issue by alno74d** [morpheus65535/bazarr#652]
Hi,
Is there a way to by-pass this configuration and make bazarr upgrade all subtitles if applicable?
![image](https://user-images.githubusercontent.com/16304323/67905834-04b08980-fb73-11e9-8715-6c29e161e2a4.png)
Thanks in advance,

**Comment by morpheus65535** [comment]
No. That prevent infinite spamming of providers.

**Comment by RogueGhost93** [comment]
Is it possible to do it through config files somehow?
I have thousands and thousands of subtitles previously downloaded which are many not correctly synced so i would like to perform a thorough clean up but i do NOT want to erase ALL subtitles in order to perform the cleanup. Many are downloaded way way earlier than just 30 days ago...is there any way to fix this?

If not, the second option is to delete all .srt files and start from scratch which will basically spam providers even more...
Thanks for help

**Comment by morpheus65535** [comment]
Not possible. Please refrain from using this issue tracker for anything else than bug report. Please come to Discord for questions.
