### ISSUE TITLE
Option to download srt regardless of embedded subtitles

### ISSUE THREAD

**Issue by JanRenkin** [morpheus65535/bazarr#69]
Hi,

I would like an option to let bazarr download a srt regardless of the video already having an embedded subtitle (it doesn't seem to recognize whether the embedded subtitle is HI or not).

Thanks

**Comment by morpheus65535** [comment]
I agree that Bazarr should have an option to ignore embedded subtitles. There’s no way for me to detect if they are HI.

**Comment by secret-liar** [comment]
I was coming on GitHub to post the exact same suggestion :D
Thanks! I have a lot of embedded subtitles that are worthless ;

**Comment by faulander** [comment]
+1 from me. 
Because of our other discussion i check a few episodes with embedded subtitles and they don't show up on Kodi for me either :(

**Comment by morpheus65535** [comment]
Would that be a global option or you would prefer to do it on an episode base?

**Comment by faulander** [comment]
for me: global. I don't mind having extra subtitles.

**Comment by secret-liar** [comment]
Same here, I need it for all tv shows :)

Le mer. 30 mai 2018, à 13 h 16, faulander <notifications@github.com> a
écrit :

**Comment by malogaudry** [comment]
+1 :)

**Comment by morpheus65535** [comment]
You can try this in dev branch. Please give me feedback!

**Comment by JanRenkin** [comment]
Tried it, works nicely!

**Comment by morpheus65535** [comment]
Good news! It was so easy to achieve I should have done it before. :-)

I’ll merge it to master in a couple of days.

**Comment by secret-liar** [comment]
Am I the only one that can't get the setting to be saved?
I can enable "Use embedded subtitles" and save settings. But if I open the page again, the toggle is off again.
I don't know when it's active or not

**Comment by morpheus65535** [comment]
It works for me.

I can deactivate it, save settings. It stay deactivated.
I can activate it, save settings. It also stay activated.

Something in browser console? Maybe a javascript error or something else?

**Comment by peskdale** [comment]
I'm having the same problem here - this setting (nor the new movies score one) has no value, nor does it store one when saved. I suspect something in my DB hasn't been updated.

Worse, because it's defaulted to false, Bazarr is now downloading subtitles for all the shows/movies that already have embedded ones!

**Comment by peskdale** [comment]
Scratch that... manually checking the DB shows it has the values I've set. It just isn't getting read for some reason.

**Comment by morpheus65535** [comment]
Ok so you got a UI bug not rendering the correct value in settings?

**Comment by peskdale** [comment]
This does not appear to be a merely a UI bug in the settings page. Despite the DB being good, all my videos with embedded subs are being flagged as missing subtitles. No amount of rescanning is fixing that, which suggests to me that this is a wider issue.

**Comment by morpheus65535** [comment]
Ok I’ll test this later and see what I can do.

**Comment by morpheus65535** [comment]
Should be all right by now... sorry, my mistake. :-/

I hope I didn't break anything else for you guys running dev branch...

**Comment by mobamoba** [comment]
I know this is closed, but I'm not sure if an issue I'm seeing is a bug or the way it's intended to work. When I tell Bazarr to ignore embedded subtitles, it also ignores MKVs with internal SRTs. Is this the intended behavior? If so, is there a way for Bazarr to only ignore graphical subtitles like PGS when determining whether or not subtitles are missing? Because otherwise, with that option enabled, Bazarr ends up downloading an SRT that already exists internally. Thanks.

**Comment by morpheus65535** [comment]
@Mobamoba if you disable ‘use embedded subtitles’, it’s a normal behavior for Bazarr to not take care of mkv embedded subtitles. You have to enable this option if you don’t want to download a srt when an embedded subtitles already exist.

**Comment by mobamoba** [comment]
I understand. I guess I was hoping that Bazarr would be able to distinguish between text-based subtitles like srt, ass, vtt, etc. image-based subtitles like pgs or sub/idx, regardless of whether or not the subtitles are embedded or external.

Since MKVs aren't consistent - some of them have no subtitles, some have text only, some have image only, and some have both - the issue to me is that "use embedded subtitles" doesn't take into account the type of subtitle. If a text subtitle already exists in the MKV and I disable "use embedded subtitles" Bazarr will then end up making unnecessary API calls to providers.

If Bazarr, rather than distinguishing between embedded vs external subtitles instead distinguished between text vs image subtitles, this would allow for text subtitle downloads without making use of unnecessary calls.

Does that make sense? Basically, when I disabled "use embedded subtitles" Bazarr was about to download 75 subtitles. When I re-enabled it and looked at my actual files, 68 of them already had SRTs in the MKV. This would have meant using 68 API calls for subtitles I already had. With distinguishing between text vs image rather than embedded vs external, Bazarr would have only made 7 API calls.

**Comment by morpheus65535** [comment]
You can have a look at ‘Ignore embedded PGS subtitles’ settings.

**Comment by mobamoba** [comment]
Apologies - Bazarr stopped auto-updating itself so wasn't on newest version and thus that option wasn't available. Thanks.
