### ISSUE TITLE
SSL ERROR After update python from 2.x to 3.7.3 -> dh_key_too_small

### ISSUE THREAD

**Issue by mclssk** [morpheus65535/bazarr#728]
Hi!

Some subtitles providers don't work after update python. 

This is my error log:

Throttling subdivx for 10 minutes, until 20/01/02 08:43, because of: SSLError. Exception info: MaxRetryError("HTTPSConnectionPool(host='www.subdivx.com', port=443): Max retries exceeded with url: /index.php?buscar=Dracula+S01E01&accion=5&oxdown=1&pg=1 (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1056)')))")

Thanks!

**Comment by morpheus65535** [comment]
This error is caused by a weak SSL certificate exposed by SubDivx. I've just tested it with Python 3.8.0 (Docker image) and cannot reproduce the issue. Can you tell me a little bit more about your setup?

**Comment by mclssk** [comment]
![image](https://user-images.githubusercontent.com/2610945/71678906-8e085600-2d86-11ea-8c1e-13b3b60694f9.png)

I have updated python, and reconfigured new requirements.txt from your repository.

And nothing more... thanks for the answer!!

**Comment by rodalpho** [comment]
The fix for this is to drop the OpenSSL SECLEVEL. Debian (and thus Ubuntu) increased it to 2 recently. On Ubuntu:

1) Edit /etc/ssl/openssl.cnf

2) At the top of the file put
openssl_conf = default_conf

3) At the bottom, put
[ default_conf ]
ssl_conf = ssl_sect
[ssl_sect]
system_default = ssl_default_sect
[ssl_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=1

4) That's it!
