### ISSUE TITLE
Provider zimuku not working

### ISSUE THREAD

**Issue by kSotin** [morpheus65535/bazarr#783]
**Describe the bug**
Provider zimuku always returns zero search results. 

**Software (please complete the following information):**
 - Bazarr: 0.8.4

**Additional context**
Related logs:

> 30/01/2020 00:35:59|INFO    |subliminal_patch.core           |Using 1 threads for 1 providers (['zimuku'])|
30/01/2020 00:35:59|INFO    |subliminal_patch.core           |Downloading best subtitles for <Movie ['Catch Me If You Can', 2002]>|
30/01/2020 00:35:59|INFO    |subliminal_patch.core           |Listing subtitles with provider 'zimuku' and languages {<Language [zh]>}|
30/01/2020 00:35:59|INFO    |subliminal_patch.core           |Initializing provider zimuku|
30/01/2020 00:35:59|DEBUG   |subliminal_patch.providers.zimuku|Searching subtitles 'Catch Me If You Can 2002'|
30/01/2020 00:35:59|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): www.zimuku.la:80|
30/01/2020 00:35:59|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on www.zimuku.la|
30/01/2020 00:36:05|DEBUG   |urllib3.connectionpool          |http://www.zimuku.la:80 "GET /search?q=Catch%20Me%20If%20You%20Can%202002 HTTP/1.1" 200 None|
30/01/2020 00:36:05|INFO    |subliminal_patch.core           |Downloaded 0 subtitle(s)|
30/01/2020 00:36:05|DEBUG   |subliminal.core                 |Terminating initialized providers|

Heres what I get when searching manually with the exactly same search string, and it's actually returning something. 
<img width="942" alt="image" src="https://user-images.githubusercontent.com/57791410/73377551-3106ae00-42fa-11ea-85be-6d0f0305566f.png">

**Comment by morpheus65535** [comment]
@jindaxia could you take a look at this one please?

**Comment by yimingzhaomath** [comment]
It looks like Zimuku's webpage style has changed dramatically since @jindaxia last implemented it. Here are the two things I observed:
Say I want to download subtitle for The Good Doctor S02E01

1. The search link created by 
```python
params = keyword
if season and episode:
            params += ' S{season:02d}E{episode:02d}'.format(season=season, episode=episode)
        elif year:
            params += ' {:4d}'.format(year)
search_link = self.server_url + text_type(self.search_url).format(params)
```

seem to create a url of the type http://www.zimuku.la/search?q=Good+Doctor+S02E01

Note the +/space/%20 in the url. Zimuku now does not return anything. Instead, you have to search for "Good.Doctor.S02.E01", which does return something, but...

2. The returned webpage instead of giving you subtitles, gives you a page where you get the whole Season 2 with a few latest subtitles displayed and a button "see the rest 20 subtitles". If you click that button, it will then take you to a page with a whole season of subtitles. 

3. Tried "Good.Doctor.S02". Not returning anything. Honestly, I don't see a logic in the search pattern.

**Comment by kSotin** [comment]
https://github.com/gyh1621/GetSubtitles

This repository contains a zimuku downloader zimuku.py that are working properly. Might be of some help for those who are into fixing this issue.

**Comment by morpheus65535** [comment]
Should be fixed in dev branch, thanks to @gyh1621
