### ISSUE TITLE
bsplayer timeouts

### ISSUE THREAD

**Issue by rigas40** [morpheus65535/bazarr#805]
HTTPConnectionPool(host='s105.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: /v1.php (Caused by ConnectTimeoutError(, 'Connection to s105.api.bsplayer-subtitles.com timed out. (connect timeout=10)')), retrying in 5 seconds...

bsplayer are always give this timouts

**Comment by GermanG** [comment]
Yes, this is because the server detects too many requests from your IP, because of that bazarr will throttle it -pause- for 10 minutes, after that, it'll resume. 
In my experience bsplayer is great finding the right subtitle (uses opensubtitles hashing) but I'm regarding it as a "upgrader" provider, ie, doesn't download right away, but eventually is going to upgrade the subtitle, if it's there, of course.
BTW: I'm the author of that provider
