### ISSUE TITLE
Supersusbtiltes, hosszupuska not working

### ISSUE THREAD

**Issue by likeaRAINBOW** [morpheus65535/bazarr#832]
**Describe the bug**
supersubtiltes and hosszpuska providet does not work

Status:  FeatureNotFound

Log message: 
Throttling supersubtitles for 10 minutes, until 20/02/22 14:23, because of: FeatureNotFound. Exception info: None

**Comment by morpheus65535** [comment]
@pannal you have the same issue upstream?

**Comment by GermanG** [comment]
@likeaRAINBOW can you provide the full logs?

**Comment by speedkup** [comment]
Hello,
This is my problem too. 

**Full logs:**

27/02/2020 02:44:49|INFO    |root                            |Using hosszupuska again after 10 minutes, (disabled because: HTTPError)|
27/02/2020 02:44:49|INFO    |root                            |Using supersubtitles again after 10 minutes, (disabled because: TypeError)|
27/02/2020 02:44:51|INFO    |root                            |Throttling hosszupuska for 10 minutes, until 20/02/27 02:54, because of: HTTPError. Exception info: '404 Client Error: Not Found for url: http://hosszupuskasub.com/!!feliratok/1207387295.zip+'|
27/02/2020 02:44:51|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 20/02/27 02:54, because of: TypeError. Exception info: 'expected str, bytes or os.PathLike object, not NoneType'|
27/02/2020 02:44:51|INFO    |root                            |BAZARR All providers are throttled|
27/02/2020 04:01:30|INFO    |root                            |BAZARR All existing episode subtitles indexed from disk.|
27/02/2020 05:00:03|INFO    |root                            |BAZARR All existing movie subtitles indexed from disk.|
27/02/2020 05:44:49|INFO    |root                            |Using hosszupuska again after 10 minutes, (disabled because: HTTPError)|
27/02/2020 05:44:49|INFO    |root                            |Using supersubtitles again after 10 minutes, (disabled because: TypeError)|
27/02/2020 05:44:51|INFO    |root                            |Throttling hosszupuska for 10 minutes, until 20/02/27 05:54, because of: HTTPError. Exception info: '404 Client Error: Not Found for url: http://hosszupuskasub.com/!!feliratok/1207387295.zip+'|
27/02/2020 05:44:51|INFO    |root                            |BAZARR No new version of Bazarr available.|
27/02/2020 05:44:51|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 20/02/27 05:54, because of: TypeError. Exception info: 'expected str, bytes or os.PathLike object, not NoneType'|
27/02/2020 05:44:51|INFO    |root                            |BAZARR All providers are throttled|
27/02/2020 08:44:49|INFO    |root                            |Using hosszupuska again after 10 minutes, (disabled because: HTTPError)|
27/02/2020 08:44:49|INFO    |root                            |Using supersubtitles again after 10 minutes, (disabled because: TypeError)|
27/02/2020 08:45:13|WARNING |retry.api                       |HTTPConnectionPool(host='hosszupuskasub.com', port=80): Max retries exceeded with url: /sorozatok.php?cim=The+Big+Bang+Theory&evad=01&resz=02&nyelvtipus=%25&x=24&y=8 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf4b902b00>: Failed to establish a new connection: [Errno 101] Network is unreachable',)), retrying in 5 seconds...|
27/02/2020 08:45:13|WARNING |retry.api                       |HTTPConnectionPool(host='hosszupuskasub.com', port=80): Max retries exceeded with url: /sorozatok.php?cim=Star+Trek:+Picard&evad=01&resz=06&nyelvtipus=%25&x=24&y=8 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faeec040d68>: Failed to establish a new connection: [Errno 101] Network is unreachable',)), retrying in 5 seconds...|
27/02/2020 08:45:21|INFO    |root                            |Throttling hosszupuska for 10 minutes, until 20/02/27 08:55, because of: HTTPError. Exception info: '404 Client Error: Not Found for url: http://hosszupuskasub.com/!!feliratok/1207387295.zip+'|
27/02/2020 08:45:30|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 20/02/27 08:55, because of: TypeError. Exception info: 'expected str, bytes or os.PathLike object, not NoneType'|
27/02/2020 08:45:30|INFO    |root                            |BAZARR All providers are throttled|
27/02/2020 10:29:56|INFO    |root                            |Using hosszupuska again after 10 minutes, (disabled because: HTTPError)|
27/02/2020 10:29:56|INFO    |root                            |Using supersubtitles again after 10 minutes, (disabled because: TypeError)|

**Comment by morpheus65535** [comment]
I've tested supersubtitles with both Python 2.7.16 and 3.8.1 and everything is working fine for me. Could you tell me more about your setup?

**Comment by likeaRAINBOW** [comment]
Sure,

branch: master
OS: Ubuntu 18.04
Python Version: 3.8.2
Bazarr Version: 0.8.4.1

I have installed with pip3 the requirements too.

The Logs show just this:

28/02/2020 22:37:22|INFO    |root                            |Using hosszupuska again after 10 minutes, (disabled because: FeatureNotFound)|
28/02/2020 22:37:22|INFO    |root                            |Using supersubtitles again after 10 minutes, (disabled because: FeatureNotFound)|

**Comment by likeaRAINBOW** [comment]
Now i upgrade to developer branch, nothing changes. I turn on debug log, here is 
[bazarr_debug.log](https://github.com/morpheus65535/bazarr/files/4269313/bazarr_debug.log)
:

**Comment by halali** [comment]
You are missing lxml library. Use pip3 install lxml

**Comment by halali** [comment]
You did not install requirements

**Comment by likeaRAINBOW** [comment]
Yes, meantime i found the problem too, i use python3.8, and the lxml library is for python 3.6

pip3 install -r requirements.txt 
Requirement already satisfied: lxml>=4.3.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1))
