### ISSUE TITLE
FreeBSD Install, Not Working

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [morpheus65535/bazarr#93]
Followed the steps for Linux, but installed the FreeBSD jpg library. I get this error trying to launch

    root@Bazarr:/Bazarr # python2.7 bazarr.py
    Traceback (most recent call last):
      File "bazarr.py", line 12, in <module>
        import sqlite3
      File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
        from dbapi2 import *
      File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
        from _sqlite3 import *
    ImportError: No module named _sqlite3

**Comment by morpheus65535** [comment]
Install databases/py-sqlite3. The python installation shows the following message when it is finished:

====
Note that some of the standard modules are provided as separate ports since they require extra dependencies:

bsddb           databases/py-bsddb
gdbm            databases/py-gdbm
sqlite3         databases/py-sqlite3
tkinter         x11-toolkits/py-tkinter

Install them as needed.
====

Source: https://lists.freebsd.org/pipermail/freebsd-questions/2011-May/230310.html

**Comment by morpheus65535** [comment]
Also take a look at:

https://stackoverflow.com/questions/37827089/how-to-use-sqlite3-in-python-on-freebsd

**Comment by Adrian-at-CrimsonAuzre** [comment]
Thanks, py-gdbm did it for me. I also had to use a different version of sqlite, the current port throws errors on any application I've tried that uses it

    pkg delete -f sqlite3
    fetch "http://pkg.freebsd.org/freebsd:11:x86:64/release_0/All/sqlite3-3.13.0.txz"
    pkg add sqlite3-*.txz

**Comment by morpheus65535** [comment]
That's quite strange and unfriendly. I'll stick to Ubuntu... ;-)

Good thing, at least you make it work! Have fun!
