### ISSUE TITLE
This doesn't work with Windows

### ISSUE THREAD

**Issue by nafeasonto** [morpheus65535/bazarr#946]
1.  Installed Python 3.82
2.  Added Pyhton to the Path
3. Installed Bazarr
4.  Restart server with Bazarr

Getting this constant Python error (amongst Access Denied, which everything in my network has full share/security access)

Job "movies_download_subtitles_550 (trigger: date[2020-04-25 20:27:00 EDT], next run at: 2020-04-25 20:27:00 EDT)" raised an exception

Then access denied errors out the ass.  Any fixes here?

**Comment by morpheus65535** [comment]
I guess you didn't read carefully the wiki... you are probably running the service as SYSTEM account that doens't have any right over the network... just in case: https://github.com/morpheus65535/bazarr/wiki

BTW over 7300 unique instance of Bazarr running on Windows have downloaded about 45 000 subtitles yesterday alone so I guess it is working...

I suggest you read the instruction on the wiki and if you need support, you come to the support channel on Discord and don't pretend this doesn't work because you can't have it working without reading the instruction.

**Comment by nafeasonto** [comment]
I am sure you are proud of the unique downloads.  But i suggest you put this under faq common issues. Because under the windows section i did not see that.

**Comment by nafeasonto** [comment]
I am also still getting:

Job "movies_download_subtitles_492 (trigger: date[2020-04-25 21:23:04 EDT], next run at: 2020-04-25 21:23:04 EDT)" raised an exception

When trying to find a subtitle, this did not fix the issue.,

**Comment by morpheus65535** [comment]
https://github.com/morpheus65535/bazarr/wiki/FAQ-Common-Problems#this-path-doesnt-seems-to-be-valid

As for this new issue, I'll be happy to get a debug an see what's going wrong. :-)

**Comment by nafeasonto** [comment]
Thankee

**Comment by nafeasonto** [comment]
How would you like me to do the log, because it keeps throwing an exception?

**Comment by morpheus65535** [comment]
Enable debug log in settings, empty log in system-->logs, reproduce the issue, disable debug log, download log from system-->logs then add it to this issue.
